### ISSUE TITLE
Webpage tells me to activate mod_rewrite, but it's activated

### ISSUE THREAD

**Issue by Hornochs** [code-boxx/Storage-Boxx-PHP-Inventory-System#5]
**Describe the bug**
Webpage shows before installation to enable MOD_Rewrite, Hoster tells me plugin is enabled

**To Reproduce**
1.  open / page

**Expected behavior**
Start Installation

**Screenshots**
![image](https://github.com/code-boxx/Storage-Boxx-PHP-Inventory-System/assets/63955136/1a6372f3-402c-4945-a060-678377b8524e)

**Additional context**
Is there maybe content for the .htaccess needed?

**Comment by code-boxx** [comment]
1) Interesting. The installer uses `apache_get_modules()` to get all the installed modules.
2) So, it's most likely an issue with your AMP stack that it's not registered.
3) Edit `lib/LIB-Install.php`, override line 25-27 to `define("I_REWRITE", true)` if you want.
